version: '3.8'

services:
  # --- DATABASES ---
  user-db:
    image: postgres:16-alpine
    container_name: user-db
    environment:
      POSTGRES_DB: user_management_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 1%51K?6TbAb$
    ports:
      - "5431:5432"

  event-db:
    image: postgres:16-alpine
    container_name: event-db
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 1%51K?6TbAb$
    ports:
      - "5432:5432"

  registration-db:
    image: postgres:16-alpine
    container_name: registration-db
    environment:
      POSTGRES_DB: registration_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: 1%51K?6TbAb$
    ports:
      - "5433:5432"

  # --- MICROSERVICES ---
  user-service:
    build: ./UserManagementService
    container_name: user-management-service
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user_management_db
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=1%51K?6TbAb$
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - user-db

  event-service:
    build: ./EventService
    container_name: event-service
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://event-db:5432/event_db
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=1%51K?6TbAb$
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - event-db

  registration-service:
    build: ./RegistrationService
    container_name: registration-service
    ports:
      - "8083:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://registration-db:5432/registration_db
      - SPRING_DATASOURCE_USERNAME=dev_user
      - SPRING_DATASOURCE_PASSWORD=1%51K?6TbAb$
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - registration-db

networks:
  default:
    name: event-management-network