apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: event-management

data:
  nginx.prod.conf: |
    events {}

    http {

      upstream user_service {
          server user-service:8081;
      }

      upstream event_service {
          server event-service:8082;
      }

      upstream registration_service {
          server registration-service:8083;
      }

      upstream notification_service {
          server notification-service:8084;
      }

      server {
          listen 80;

          location /api/users/ {
              proxy_pass http://user_service/;
          }

          location /api/events/ {
              proxy_pass http://event_service/;
          }

          location /api/registrations/ {
              proxy_pass http://registration_service/;
          }

          location /api/notifications/ {
              proxy_pass http://notification_service/;
          }
      }
    }