apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: event-management
spec:
  template:
    spec:
      containers:
        - name: user-service
          image: user-service:latest
          envFrom:
            - configMapRef:
                name: app-config

data:
  RABBITMQ_HOST: rabbitmq

  USER_SERVICE_URL: http://user-service:8081
  EVENT_SERVICE_URL: http://event-service:8082
  REGISTRATION_SERVICE_URL: http://registration-service:8083
  NOTIFICATION_SERVICE_URL: http://notification-service:8084

  DB_PORT: "5432"

  SPRING_PROFILES_ACTIVE: prod