apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: event-management
type: Opaque
stringData:
  JWT_SECRET: 2ebc9101f2415cd8dc57becf0cd727fd3c30b0f9da6584661243321659cdf945
  POSTGRES_PASSWORD: postgres
  RABBITMQ_PASSWORD: guest