apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: event-management
type: Opaque
stringData:
  jwt-secret: "7fede8b2e8e7e352094ace5e4e1aaa699ea96a8b2951da96dd3f392bcab8b7f1"
  db-password: "postgres"
  rabbitmq-user: "guest"
  rabbitmq-password: "guest"